apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-http
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/c-buisson/temp_eks.git
    targetRevision: HEAD
    path: '.'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
