apiVersion: v1
kind: Service
metadata:
  name: simple-http
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test-simple.dev.kyte-internal.com
spec:
  type: LoadBalancer
  selector:
    app: simple-http
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
